language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "pypy"
    - "pypy3"
install:
    - "python setup.py develop"
    - "pip install gites[tests] coveralls pylama pyroma"
    # manually install wheel for deployment
    - "pip install wheel"
script:
    - "py.test -v --cov gites tests/"
    - "pylama"
    - "pyroma"
after_success:
    - coveralls

deploy:
    provider: pypi
    user: ktrebicki
    password:
        secure: "run travis encrypt --add deploy.password"
    on:
        tags: true
        all_branches: true
        repo: ktrebicki/gites
    distributions: "sdist bdist_wheel"
